spring:
  datasource:
    drivername: com.mysql.cj.jdbc.Driver
    password: Zmy12345678
    url: jdbc:mysql://localhost:3306/Angent?characterEncoding=utf-8&serverTimezone=GMT+8&useSSL=false&serverTimezone=UTC
    username: root
    sqlName: Angent

#生成xml的包名位置
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  path: log
  config: classpath:config/logback-spring.xml

